/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PairRouteImport } from './routes/pair'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as ElderRouteImport } from './routes/elder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianIndexRouteImport } from './routes/guardian.index'
import { Route as ElderIndexRouteImport } from './routes/elder.index'
import { Route as GuardianProfileRouteImport } from './routes/guardian.profile'
import { Route as GuardianPersonalizeRouteImport } from './routes/guardian.personalize'
import { Route as GuardianNotificationsRouteImport } from './routes/guardian.notifications'
import { Route as GuardianMemoryRouteImport } from './routes/guardian.memory'
import { Route as GuardianMedicationsRouteImport } from './routes/guardian.medications'
import { Route as GuardianDashboardRouteImport } from './routes/guardian.dashboard'
import { Route as GuardianCallsRouteImport } from './routes/guardian.calls'
import { Route as GuardianAlertsRouteImport } from './routes/guardian.alerts'
import { Route as ElderSettingsRouteImport } from './routes/elder.settings'
import { Route as ElderHomeRouteImport } from './routes/elder.home'
import { Route as ElderCallingRouteImport } from './routes/elder.calling'
import { Route as GuardianReportsWeeklyRouteImport } from './routes/guardian.reports.weekly'
import { Route as GuardianCallsCallIdRouteImport } from './routes/guardian.calls.$callId'

const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderRoute = ElderRouteImport.update({
  id: '/elder',
  path: '/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianIndexRoute = GuardianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardianRoute,
} as any)
const ElderIndexRoute = ElderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElderRoute,
} as any)
const GuardianProfileRoute = GuardianProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianPersonalizeRoute = GuardianPersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianNotificationsRoute = GuardianNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianMemoryRoute = GuardianMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianMedicationsRoute = GuardianMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianCallsRoute = GuardianCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianAlertsRoute = GuardianAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => GuardianRoute,
} as any)
const ElderSettingsRoute = ElderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ElderRoute,
} as any)
const ElderHomeRoute = ElderHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ElderRoute,
} as any)
const ElderCallingRoute = ElderCallingRouteImport.update({
  id: '/calling',
  path: '/calling',
  getParentRoute: () => ElderRoute,
} as any)
const GuardianReportsWeeklyRoute = GuardianReportsWeeklyRouteImport.update({
  id: '/reports/weekly',
  path: '/reports/weekly',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianCallsCallIdRoute = GuardianCallsCallIdRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => GuardianCallsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/elder': typeof ElderRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/pair': typeof PairRoute
  '/elder/calling': typeof ElderCallingRoute
  '/elder/home': typeof ElderHomeRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/calls': typeof GuardianCallsRouteWithChildren
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/memory': typeof GuardianMemoryRoute
  '/guardian/notifications': typeof GuardianNotificationsRoute
  '/guardian/personalize': typeof GuardianPersonalizeRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/elder/': typeof ElderIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/calls/$callId': typeof GuardianCallsCallIdRoute
  '/guardian/reports/weekly': typeof GuardianReportsWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pair': typeof PairRoute
  '/elder/calling': typeof ElderCallingRoute
  '/elder/home': typeof ElderHomeRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/calls': typeof GuardianCallsRouteWithChildren
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/memory': typeof GuardianMemoryRoute
  '/guardian/notifications': typeof GuardianNotificationsRoute
  '/guardian/personalize': typeof GuardianPersonalizeRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/elder': typeof ElderIndexRoute
  '/guardian': typeof GuardianIndexRoute
  '/guardian/calls/$callId': typeof GuardianCallsCallIdRoute
  '/guardian/reports/weekly': typeof GuardianReportsWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/elder': typeof ElderRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/pair': typeof PairRoute
  '/elder/calling': typeof ElderCallingRoute
  '/elder/home': typeof ElderHomeRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/calls': typeof GuardianCallsRouteWithChildren
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/memory': typeof GuardianMemoryRoute
  '/guardian/notifications': typeof GuardianNotificationsRoute
  '/guardian/personalize': typeof GuardianPersonalizeRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/elder/': typeof ElderIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/calls/$callId': typeof GuardianCallsCallIdRoute
  '/guardian/reports/weekly': typeof GuardianReportsWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/elder'
    | '/guardian'
    | '/pair'
    | '/elder/calling'
    | '/elder/home'
    | '/elder/settings'
    | '/guardian/alerts'
    | '/guardian/calls'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/memory'
    | '/guardian/notifications'
    | '/guardian/personalize'
    | '/guardian/profile'
    | '/elder/'
    | '/guardian/'
    | '/guardian/calls/$callId'
    | '/guardian/reports/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pair'
    | '/elder/calling'
    | '/elder/home'
    | '/elder/settings'
    | '/guardian/alerts'
    | '/guardian/calls'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/memory'
    | '/guardian/notifications'
    | '/guardian/personalize'
    | '/guardian/profile'
    | '/elder'
    | '/guardian'
    | '/guardian/calls/$callId'
    | '/guardian/reports/weekly'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/elder'
    | '/guardian'
    | '/pair'
    | '/elder/calling'
    | '/elder/home'
    | '/elder/settings'
    | '/guardian/alerts'
    | '/guardian/calls'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/memory'
    | '/guardian/notifications'
    | '/guardian/personalize'
    | '/guardian/profile'
    | '/elder/'
    | '/guardian/'
    | '/guardian/calls/$callId'
    | '/guardian/reports/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ElderRoute: typeof ElderRouteWithChildren
  GuardianRoute: typeof GuardianRouteWithChildren
  PairRoute: typeof PairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder': {
      id: '/elder'
      path: '/elder'
      fullPath: '/elder'
      preLoaderRoute: typeof ElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/': {
      id: '/guardian/'
      path: '/'
      fullPath: '/guardian/'
      preLoaderRoute: typeof GuardianIndexRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/elder/': {
      id: '/elder/'
      path: '/'
      fullPath: '/elder/'
      preLoaderRoute: typeof ElderIndexRouteImport
      parentRoute: typeof ElderRoute
    }
    '/guardian/profile': {
      id: '/guardian/profile'
      path: '/profile'
      fullPath: '/guardian/profile'
      preLoaderRoute: typeof GuardianProfileRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/personalize': {
      id: '/guardian/personalize'
      path: '/personalize'
      fullPath: '/guardian/personalize'
      preLoaderRoute: typeof GuardianPersonalizeRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/notifications': {
      id: '/guardian/notifications'
      path: '/notifications'
      fullPath: '/guardian/notifications'
      preLoaderRoute: typeof GuardianNotificationsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/memory': {
      id: '/guardian/memory'
      path: '/memory'
      fullPath: '/guardian/memory'
      preLoaderRoute: typeof GuardianMemoryRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/medications': {
      id: '/guardian/medications'
      path: '/medications'
      fullPath: '/guardian/medications'
      preLoaderRoute: typeof GuardianMedicationsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/calls': {
      id: '/guardian/calls'
      path: '/calls'
      fullPath: '/guardian/calls'
      preLoaderRoute: typeof GuardianCallsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/alerts': {
      id: '/guardian/alerts'
      path: '/alerts'
      fullPath: '/guardian/alerts'
      preLoaderRoute: typeof GuardianAlertsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/elder/settings': {
      id: '/elder/settings'
      path: '/settings'
      fullPath: '/elder/settings'
      preLoaderRoute: typeof ElderSettingsRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/home': {
      id: '/elder/home'
      path: '/home'
      fullPath: '/elder/home'
      preLoaderRoute: typeof ElderHomeRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/calling': {
      id: '/elder/calling'
      path: '/calling'
      fullPath: '/elder/calling'
      preLoaderRoute: typeof ElderCallingRouteImport
      parentRoute: typeof ElderRoute
    }
    '/guardian/reports/weekly': {
      id: '/guardian/reports/weekly'
      path: '/reports/weekly'
      fullPath: '/guardian/reports/weekly'
      preLoaderRoute: typeof GuardianReportsWeeklyRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/calls/$callId': {
      id: '/guardian/calls/$callId'
      path: '/$callId'
      fullPath: '/guardian/calls/$callId'
      preLoaderRoute: typeof GuardianCallsCallIdRouteImport
      parentRoute: typeof GuardianCallsRoute
    }
  }
}

interface ElderRouteChildren {
  ElderCallingRoute: typeof ElderCallingRoute
  ElderHomeRoute: typeof ElderHomeRoute
  ElderSettingsRoute: typeof ElderSettingsRoute
  ElderIndexRoute: typeof ElderIndexRoute
}

const ElderRouteChildren: ElderRouteChildren = {
  ElderCallingRoute: ElderCallingRoute,
  ElderHomeRoute: ElderHomeRoute,
  ElderSettingsRoute: ElderSettingsRoute,
  ElderIndexRoute: ElderIndexRoute,
}

const ElderRouteWithChildren = ElderRoute._addFileChildren(ElderRouteChildren)

interface GuardianCallsRouteChildren {
  GuardianCallsCallIdRoute: typeof GuardianCallsCallIdRoute
}

const GuardianCallsRouteChildren: GuardianCallsRouteChildren = {
  GuardianCallsCallIdRoute: GuardianCallsCallIdRoute,
}

const GuardianCallsRouteWithChildren = GuardianCallsRoute._addFileChildren(
  GuardianCallsRouteChildren,
)

interface GuardianRouteChildren {
  GuardianAlertsRoute: typeof GuardianAlertsRoute
  GuardianCallsRoute: typeof GuardianCallsRouteWithChildren
  GuardianDashboardRoute: typeof GuardianDashboardRoute
  GuardianMedicationsRoute: typeof GuardianMedicationsRoute
  GuardianMemoryRoute: typeof GuardianMemoryRoute
  GuardianNotificationsRoute: typeof GuardianNotificationsRoute
  GuardianPersonalizeRoute: typeof GuardianPersonalizeRoute
  GuardianProfileRoute: typeof GuardianProfileRoute
  GuardianIndexRoute: typeof GuardianIndexRoute
  GuardianReportsWeeklyRoute: typeof GuardianReportsWeeklyRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianAlertsRoute: GuardianAlertsRoute,
  GuardianCallsRoute: GuardianCallsRouteWithChildren,
  GuardianDashboardRoute: GuardianDashboardRoute,
  GuardianMedicationsRoute: GuardianMedicationsRoute,
  GuardianMemoryRoute: GuardianMemoryRoute,
  GuardianNotificationsRoute: GuardianNotificationsRoute,
  GuardianPersonalizeRoute: GuardianPersonalizeRoute,
  GuardianProfileRoute: GuardianProfileRoute,
  GuardianIndexRoute: GuardianIndexRoute,
  GuardianReportsWeeklyRoute: GuardianReportsWeeklyRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ElderRoute: ElderRouteWithChildren,
  GuardianRoute: GuardianRouteWithChildren,
  PairRoute: PairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
